### ISSUE TITLE
Feature Request: Possible integration with docker to run locally

### ISSUE THREAD

**Issue by Shrink6881** [KrishnaSSH/Memes-API#1]
I am suggesting and possibly contributing the creation of a docker image / Docker file to allow downloading without an external server.

PS: First time posting an issue / feature request

**Comment by KrishnaSSH** [comment]
Thank you so much for suggesting this and for adding your first issue! 
Probably a Dockerfile makes sense. It would make for a much more streamlined process.

This project was actually on my roadmap to rewrite from scratch with proper dynamic and much better front end as coincidence. Which means You may not want to do this rn but after the next update coming soon :)
